export const moviesList = [
  {
    id: 1,
    title: 'Movie Name One',
    description: 'This is movie description one',
    thumbnail: 'https://dummyimage.com/250x400/cccccc/ffffff.png',
    rating: '3',
    year: '2004',
    duration: '90',
    genre: 'Action',
  },
  {
    id: 2,
    title: 'Movie Name Two',
    description: 'This is movie description two',
    thumbnail: 'https://dummyimage.com/250x400/cccccc/ffffff.png',
    rating: '3',
    year: '2004',
    duration: '90',
    genre: 'Action',
  },
  {
    id: 3,
    title: 'Movie Name Three',
    description: 'This is movie description three',
    thumbnail: 'https://dummyimage.com/250x400/cccccc/ffffff.png',
    rating: '3',
    year: '2004',
    duration: '90',
    genre: 'Action',
  },
  {
    id: 4,
    title: 'Movie Name Four',
    description: 'This is movie description four',
    thumbnail: 'https://dummyimage.com/250x400/cccccc/ffffff.png',
    rating: '3',
    year: '2004',
    duration: '90',
    genre: 'Action',
  },
  {
    id: 5,
    title: 'Movie Name Five',
    description: 'This is movie description five',
    thumbnail: 'https://dummyimage.com/250x400/cccccc/ffffff.png',
    rating: '3',
    year: '2004',
    duration: '90',
    genre: 'Action',
  },
  {
    id: 6,
    title: 'Movie Name Six',
    description: 'This is movie description six',
    thumbnail: 'https://dummyimage.com/250x400/cccccc/ffffff.png',
    rating: '3',
    year: '2004',
    duration: '90',
    genre: 'Action',
  },
];

export const AnotherValue = 'Booom!!!';
